CREATE TABLE jurnal_apeluri (
    id_jurnal NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nume_proc VARCHAR2(100),
    moment_start DATE,
    moment_end DATE,
    durata_secunde NUMBER,
    status_rulare VARCHAR2(20),
    mesaj_eroare VARCHAR2(4000)
);

--Specificatie pachet 
CREATE OR REPLACE PACKAGE pkg_studenti AS
   
    --procedura de loguri 
    PROCEDURE log_jurnal(
        p_nume_proc VARCHAR2,
        p_start DATE,
        p_end DATE,
        p_status VARCHAR2,
        p_mesaj_eroare VARCHAR2
    );
    
    
    PROCEDURE studenti_sectie(
        p_cod_sectia NUMBER,
        p_grupa VARCHAR2
    );

    PROCEDURE top3_grupa(
        p_grupa VARCHAR2,
        p_medie NUMBER
    );


END pkg_studenti;
/

--Corp pachet 
CREATE OR REPLACE PACKAGE BODY pkg_studenti AS

   PROCEDURE log_jurnal(
    p_nume_proc VARCHAR2,
    p_start DATE,
    p_end DATE,
    p_status VARCHAR2,
    p_mesaj_eroare VARCHAR2
) IS
    PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
    INSERT INTO jurnal_apeluri(
        nume_proc,
        moment_start,
        moment_end,
        durata_secunde,
        status_rulare,
        mesaj_eroare
    )
    VALUES (
        p_nume_proc,
        p_start,
        p_end,
        (p_end - p_start) * 86400,
        p_status,
        p_mesaj_eroare
    );

    COMMIT;
END;


    PROCEDURE top3_grupa(
        p_grupa VARCHAR2,
        p_medie NUMBER
    ) IS
        v_start DATE := SYSDATE;
    BEGIN
        FOR r IN (
            SELECT *
            FROM top_medii
            WHERE grupa = p_grupa
              AND media = p_medie
        )
        LOOP
            DBMS_OUTPUT.PUT_LINE(
                r.nume || ' ' || r.prenume ||
                ', grupa=' || r.grupa ||
                ', media=' || r.media ||
                ', pozitie=' || r.poz_student_grupa
            );
        END LOOP;

        log_jurnal('top3_grupa', v_start, SYSDATE, 'SUCCESS', NULL);
    EXCEPTION
        WHEN OTHERS THEN
            log_jurnal('top3_grupa', v_start, SYSDATE, 'ERROR', SQLERRM);
            RAISE;
    END;


    PROCEDURE studenti_sectie(
        p_cod_sectia NUMBER,
        p_grupa VARCHAR2
    ) IS
        v_start DATE := SYSDATE;
    BEGIN
        FOR r IN (
            SELECT *
            FROM info_studenti
            WHERE cod_sectia = p_cod_sectia
              AND grupa = p_grupa
        )
        LOOP
            DBMS_OUTPUT.PUT_LINE(
                r.nume || ' ' || r.prenume ||
                ', sectie=' || r.denumire_sectia ||
                ', an=' || r.an_studiu ||
                ', grupa=' || r.grupa ||
                ', media=' || r.media
            );
        END LOOP;

        log_jurnal('studenti_sectie_si_grupa', v_start, SYSDATE, 'SUCCESS', NULL);
    EXCEPTION
        WHEN OTHERS THEN
            log_jurnal('studenti_sectie_si_grupa', v_start, SYSDATE, 'ERROR', SQLERRM);
            RAISE;
    END;

END pkg_studenti;
/

SET SERVEROUTPUT ON;

EXEC pkg_studenti.top3_grupa('111', 7);
EXEC pkg_studenti.studenti_sectie(2, '214');
SELECT * FROM jurnal_apeluri;
