
CREATE TABLE "STUDENTI" 
   (	"NUME" CHAR(30 BYTE), 
	"PRENUME" CHAR(30 BYTE), 
	"COD_SECTIA" NUMBER(3,0), 
	"DENUMIRE_SECTIA" VARCHAR2(70 BYTE), 
	"AN_STUDIU" NUMBER(1,0), 
	"GRUPA" CHAR(10 BYTE), 
	"MEDIA" NUMBER(5,2)
   ) ;

ALTER SESSION SET NLS_NUMERIC_CHARACTERS=',.';

Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Popescu','Andrei','22','Informatica - în limba engleza','1','911       ','5,1');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Ionescu','Maria','22','Informatica - în limba engleza','1','912       ','8,06');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Georgescu','Alexandru','22','Informatica - în limba engleza','1','912       ','7,46');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Dumitrescu','Elena','22','Informatica - în limba engleza','1','912       ','8,46');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Stan','Mihai','2','Informatica - linia de studiu romana','1','215       ','6,32');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Popa','Ioana','2','Informatica - linia de studiu romana','1','216       ','9,3');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Radu','Vlad','22','Informatica - în limba engleza','3','933       ','6,89');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Marin','Ana','22','Informatica - în limba engleza','3','933       ','9,91');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Voicu','Cristian','22','Informatica - în limba engleza','3','933       ','6,76');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Moldovan','Diana','22','Informatica - în limba engleza','3','932       ','9,68');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Tudor','Paul','22','Informatica - în limba engleza','2','921       ','9,22');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Barbu','Raluca','22','Informatica - în limba engleza','2','922       ','7,8');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Neagu','Zoltan','11','Matematica - linia de studiu maghiara','1','411       ','7,28');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Lazar','Denisa','22','Informatica - în limba engleza','1','913       ','7,89');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Costache','Bogdan','22','Informatica - în limba engleza','1','914       ','8,4');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Serban','Attila','12','Informatica - linia de studiu maghiara','1','511       ','5,47');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Enache','Robert','2','Informatica - linia de studiu romana','4','242       ','7,74');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Dobre','Larisa','3','Matematica-Informatica - linia de studiu romana','4','342       ','5,74');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Stoica','Cosmin','3','Matematica-Informatica - linia de studiu romana','4','342       ','9,91');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Preda','Simona','2','Informatica - linia de studiu romana','3','232       ','5,1');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Ilie','George','3','Matematica-Informatica - linia de studiu romana','3','331       ','5,45');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Sandu','Adina','3','Matematica-Informatica - linia de studiu romana','3','331       ','6,85');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Florea','Ciprian','22','Informatica - în limba engleza','2','923       ','8,29');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nistor','Bianca','22','Informatica - în limba engleza','2','923       ','8,52');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Oprea','Sorin','2','Informatica - linia de studiu romana','3','233       ','9,28');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Pavel','Alina','2','Informatica - linia de studiu romana','3','233       ','6,25');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Morar','Teodor','22','Informatica - în limba engleza','2','922       ','7,12');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Badea','Irina','12','Informatica - linia de studiu maghiara','2','521       ','8,16');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Dragomir','Carmen','12','Informatica - linia de studiu maghiara','2','521       ','8,71');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Petrescu','Victor','12','Informatica - linia de studiu maghiara','2','521       ','6,02');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Popescu','Andrei','12','Informatica - linia de studiu maghiara','2','521       ','5,87');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Ionescu','Maria','12','Informatica - linia de studiu maghiara','1','511       ','9,73');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Georgescu','Alexandru','2','Informatica - linia de studiu romana','1','211       ','9,63');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Dumitrescu','Elena','2','Informatica - linia de studiu romana','1','212       ','6,33');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Stan','Mihai','2','Informatica - linia de studiu romana','1','212       ','8,7');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Popa','Ioana','3','Matematica-Informatica - linia de studiu romana','1','311       ','8,2');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Radu','Vlad','3','Matematica-Informatica - linia de studiu romana','1','311       ','9,67');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Marin','Ana','2','Informatica - linia de studiu romana','3','231       ','5,31');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Voicu','Cristian','2','Informatica - linia de studiu romana','3','232       ','5,55');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Moldovan','Diana','22','Informatica - în limba engleza','1','914       ','5,86');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Tudor','Paul','22','Informatica - în limba engleza','1','914       ','6,66');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Barbu','Raluca','22','Informatica - în limba engleza','1','914       ','5,91');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Neagu','Zoltan','22','Informatica - în limba engleza','1','915       ','6,37');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Lazar','Denisa','22','Informatica - în limba engleza','2','923       ','9,32');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Costache','Bogdan','2','Informatica - linia de studiu romana','4','243       ','8,02');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Serban','Attila','22','Informatica - în limba engleza','1','915       ','5,05');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Enache','Robert','1','Matematica - linia de studiu romana','3','131       ','5,78');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Dobre','Larisa','2','Informatica - linia de studiu romana','2','224       ','6,21');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Stoica','Cosmin','3','Matematica-Informatica - linia de studiu romana','2','321       ','7,82');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Preda','Simona','3','Matematica-Informatica - linia de studiu romana','2','321       ','5,63');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Ilie','George','2','Informatica - linia de studiu romana','2','223       ','5,27');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Sandu','Adina','2','Informatica - linia de studiu romana','4','242       ','7,23');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Florea','Ciprian','2','Informatica - linia de studiu romana','2','221       ','8,99');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nistor','Bianca','22','Informatica - în limba engleza','2','922       ','8,36');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Oprea','Sorin','2','Informatica - linia de studiu romana','3','231       ','7,32');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Pavel','Alina','2','Informatica - linia de studiu romana','2','224       ','9,37');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Morar','Teodor','22','Informatica - în limba engleza','2','923       ','9,31');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Badea','Irina','2','Informatica - linia de studiu romana','1','218       ','9,59');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Dragomir','Carmen','2','Informatica - linia de studiu romana','4','241       ','6,62');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Petrescu','Victor','22','Informatica - în limba engleza','4','941       ','5,02');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Popescu','Andrei','22','Informatica - în limba engleza','4','941       ','5,31');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Ionescu','Maria','22','Informatica - în limba engleza','4','943       ','7,76');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Georgescu','Alexandru','22','Informatica - în limba engleza','4','943       ','9,65');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Dumitrescu','Elena','22','Informatica - în limba engleza','4','943       ','6,4');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Stan','Mihai','22','Informatica - în limba engleza','3','931       ','6');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Popa','Ioana','22','Informatica - în limba engleza','2','921       ','7,92');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Radu','Vlad','22','Informatica - în limba engleza','1','911       ','6');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Marin','Ana','22','Informatica - în limba engleza','1','912       ','6,95');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Voicu','Cristian','22','Informatica - în limba engleza','1','912       ','8,19');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Moldovan','Diana','2','Informatica - linia de studiu romana','1','213       ','8,95');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Tudor','Paul','2','Informatica - linia de studiu romana','1','213       ','6,33');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Barbu','Raluca','2','Informatica - linia de studiu romana','1','214       ','9,4');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Neagu','Zoltan','2','Informatica - linia de studiu romana','1','216       ','6,65');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Lazar','Denisa','22','Informatica - în limba engleza','3','933       ','6,28');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Costache','Bogdan','3','Matematica-Informatica - linia de studiu romana','4','341       ','9,41');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Serban','Attila','3','Matematica-Informatica - linia de studiu romana','3','332       ','8,46');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Enache','Robert','22','Informatica - în limba engleza','1','913       ','6,91');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Dobre','Larisa','22','Informatica - în limba engleza','1','913       ','9,06');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Stoica','Cosmin','22','Informatica - în limba engleza','1','913       ','9,73');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Preda','Simona','12','Informatica - linia de studiu maghiara','1','511       ','7,1');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Ilie','George','12','Informatica - linia de studiu maghiara','1','512       ','6,88');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Sandu','Adina','12','Informatica - linia de studiu maghiara','1','512       ','7,39');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Florea','Ciprian','12','Informatica - linia de studiu maghiara','1','512       ','5,39');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nistor','Bianca','12','Informatica - linia de studiu maghiara','1','513       ','7,69');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Oprea','Sorin','12','Informatica - linia de studiu maghiara','4','541       ','9,37');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Pavel','Alina','12','Informatica - linia de studiu maghiara','4','541       ','8,2');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Morar','Teodor','3','Matematica-Informatica - linia de studiu romana','4','342       ','9,11');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Badea','Irina','22','Informatica - în limba engleza','1','913       ','8,95');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Dragomir','Carmen','22','Informatica - în limba engleza','1','913       ','5,91');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Petrescu','Victor','22','Informatica - în limba engleza','2','923       ','5,33');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Popescu','Andrei','22','Informatica - în limba engleza','2','923       ','8,23');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Ionescu','Maria','2','Informatica - linia de studiu romana','3','233       ','9,98');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Georgescu','Alexandru','12','Informatica - linia de studiu maghiara','3','531       ','8,07');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Dumitrescu','Elena','12','Informatica - linia de studiu maghiara','3','531       ','5,2');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Stan','Mihai','2','Informatica - linia de studiu romana','1','211       ','7,26');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Popa','Ioana','2','Informatica - linia de studiu romana','1','212       ','7,66');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Radu','Vlad','3','Matematica-Informatica - linia de studiu romana','1','311       ','8,83');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Marin','Ana','3','Matematica-Informatica - linia de studiu romana','1','311       ','7,37');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Voicu','Cristian','2','Informatica - linia de studiu romana','3','231       ','6,27');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Moldovan','Diana','22','Informatica - în limba engleza','1','914       ','6,21');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Tudor','Paul','22','Informatica - în limba engleza','1','915       ','9');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Barbu','Raluca','2','Informatica - linia de studiu romana','4','241       ','7,11');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Neagu','Zoltan','2','Informatica - linia de studiu romana','4','244       ','5,6');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Lazar','Denisa','22','Informatica - în limba engleza','2','921       ','9,47');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Costache','Bogdan','2','Informatica - linia de studiu romana','4','244       ','6,91');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Serban','Attila','2','Informatica - linia de studiu romana','2','224       ','9,68');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Enache','Robert','22','Informatica - în limba engleza','2','921       ','5,7');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Dobre','Larisa','2','Informatica - linia de studiu romana','2','222       ','5,89');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Stoica','Cosmin','22','Informatica - în limba engleza','3','931       ','7,42');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Preda','Simona','22','Informatica - în limba engleza','1','911       ','7,05');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Ilie','George','22','Informatica - în limba engleza','2','921       ','6,47');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Sandu','Adina','2','Informatica - linia de studiu romana','1','213       ','6,2');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Florea','Ciprian','2','Informatica - linia de studiu romana','1','216       ','6,98');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nistor','Bianca','2','Informatica - linia de studiu romana','1','217       ','7,02');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Oprea','Sorin','22','Informatica - în limba engleza','3','932       ','7,72');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Pavel','Alina','3','Matematica-Informatica - linia de studiu romana','4','341       ','9,69');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Morar','Teodor','3','Matematica-Informatica - linia de studiu romana','3','332       ','5,96');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Badea','Irina','21','Matematica-Informatica -linia de studiu germana','4','741       ','8,76');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Dragomir','Carmen','22','Informatica - în limba engleza','1','913       ','5,34');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Petrescu','Victor','22','Informatica - în limba engleza','1','914       ','6,92');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Popescu','Andrei','12','Informatica - linia de studiu maghiara','1','511       ','8,25');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Ionescu','Maria','3','Matematica-Informatica - linia de studiu romana','4','342       ','9,23');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Georgescu','Alexandru','2','Informatica - linia de studiu romana','3','232       ','6,93');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Dumitrescu','Elena','3','Matematica-Informatica - linia de studiu romana','3','332       ','6,26');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Stan','Mihai','22','Informatica - în limba engleza','2','923       ','9,15');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Popa','Ioana','22','Informatica - în limba engleza','2','923       ','8,59');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Radu','Vlad','22','Informatica - în limba engleza','2','923       ','7,06');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Marin','Ana','2','Informatica - linia de studiu romana','3','232       ','5,48');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Voicu','Cristian','2','Informatica - linia de studiu romana','3','233       ','8,65');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Moldovan','Diana','2','Informatica - linia de studiu romana','3','233       ','5,68');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Tudor','Paul','2','Informatica - linia de studiu romana','3','233       ','9,67');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Barbu','Raluca','2','Informatica - linia de studiu romana','1','212       ','5,9');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Neagu','Zoltan','2','Informatica - linia de studiu romana','1','212       ','6,17');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Lazar','Denisa','22','Informatica - în limba engleza','1','914       ','5,33');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Costache','Bogdan','1','Matematica - linia de studiu romana','1','111       ','6,57');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Serban','Attila','1','Matematica - linia de studiu romana','1','111       ','8,8');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Enache','Robert','2','Informatica - linia de studiu romana','4','241       ','7,07');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Dobre','Larisa','22','Informatica - în limba engleza','1','915       ','6,09');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Stoica','Cosmin','22','Informatica - în limba engleza','1','915       ','8,58');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Preda','Simona','22','Informatica - în limba engleza','2','921       ','6,8');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Ilie','George','2','Informatica - linia de studiu romana','4','244       ','5,25');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Sandu','Adina','1','Matematica - linia de studiu romana','4','141       ','5,58');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Florea','Ciprian','1','Matematica - linia de studiu romana','3','131       ','5,14');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nistor','Bianca','2','Informatica - linia de studiu romana','4','244       ','7,89');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Oprea','Sorin','22','Informatica - în limba engleza','3','932       ','7,34');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Pavel','Alina','22','Informatica - în limba engleza','2','922       ','5,94');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Morar','Teodor','2','Informatica - linia de studiu romana','1','218       ','9,67');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Badea','Irina','43','Baze de date','1','253       ','9,03');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Dragomir','Carmen','22','Informatica - în limba engleza','2','921       ','8,96');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Petrescu','Victor','2','Informatica - linia de studiu romana','2','221       ','7,6');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Popescu','Andrei','2','Informatica - linia de studiu romana','2','221       ','9,57');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Ionescu','Maria','2','Informatica - linia de studiu romana','2','221       ','7,08');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Georgescu','Alexandru','2','Informatica - linia de studiu romana','2','223       ','6,6');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Dumitrescu','Elena','2','Informatica - linia de studiu romana','1','217       ','8,2');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Stan','Mihai','2','Informatica - linia de studiu romana','3','233       ','7,47');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Popa','Ioana','2','Informatica - linia de studiu romana','2','221       ','8,15');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Radu','Vlad','22','Informatica - în limba engleza','4','941       ','5,7');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Marin','Ana','22','Informatica - în limba engleza','4','943       ','7,66');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Voicu','Cristian','22','Informatica - în limba engleza','4','943       ','9,95');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Moldovan','Diana','22','Informatica - în limba engleza','4','942       ','5,56');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Tudor','Paul','22','Informatica - în limba engleza','4','942       ','5,36');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Barbu','Raluca','2','Informatica - linia de studiu romana','4','241       ','5,37');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Neagu','Zoltan','12','Informatica - linia de studiu maghiara','2','521       ','6,79');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Lazar','Denisa','22','Informatica - în limba engleza','3','932       ','8,59');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Costache','Bogdan','22','Informatica - în limba engleza','1','911       ','7,39');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Serban','Attila','22','Informatica - în limba engleza','1','912       ','8,04');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Enache','Robert','22','Informatica - în limba engleza','1','912       ','9,99');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Dobre','Larisa','22','Informatica - în limba engleza','1','912       ','9,05');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Stoica','Cosmin','2','Informatica - linia de studiu romana','1','213       ','8,1');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Preda','Simona','2','Informatica - linia de studiu romana','1','214       ','6,3');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Ilie','George','2','Informatica - linia de studiu romana','1','214       ','6,48');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Sandu','Adina','2','Informatica - linia de studiu romana','1','215       ','6,21');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Florea','Ciprian','3','Matematica-Informatica - linia de studiu romana','4','341       ','9,34');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nistor','Bianca','3','Matematica-Informatica - linia de studiu romana','4','342       ','5,49');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Oprea','Sorin','3','Matematica-Informatica - linia de studiu romana','4','342       ','9,81');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Pavel','Alina','3','Matematica-Informatica - linia de studiu romana','3','332       ','5,59');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Morar','Teodor','22','Informatica - în limba engleza','1','914       ','5,17');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Badea','Irina','12','Informatica - linia de studiu maghiara','1','512       ','6,6');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Dragomir','Carmen','2','Informatica - linia de studiu romana','4','243       ','5,29');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Petrescu','Victor','2','Informatica - linia de studiu romana','4','242       ','8,1');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Popescu','Andrei','12','Informatica - linia de studiu maghiara','3','531       ','6,19');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Ionescu','Maria','2','Informatica - linia de studiu romana','4','242       ','6,63');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Georgescu','Alexandru','22','Informatica - în limba engleza','1','913       ','7,55');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Dumitrescu','Elena','22','Informatica - în limba engleza','2','923       ','5,25');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Stan','Mihai','22','Informatica - în limba engleza','2','923       ','8,87');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Popa','Ioana','2','Informatica - linia de studiu romana','3','233       ','7,15');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Radu','Vlad','12','Informatica - linia de studiu maghiara','3','531       ','9,05');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Marin','Ana','12','Informatica - linia de studiu maghiara','2','521       ','6,87');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Voicu','Cristian','2','Informatica - linia de studiu romana','1','211       ','7,99');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Moldovan','Diana','2','Informatica - linia de studiu romana','1','214       ','6,52');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Tudor','Paul','2','Informatica - linia de studiu romana','2','223       ','9,36');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Barbu','Raluca','2','Informatica - linia de studiu romana','3','231       ','7,43');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Neagu','Zoltan','2','Informatica - linia de studiu romana','2','221       ','6,46');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Lazar','Denisa','22','Informatica - în limba engleza','1','914       ','5,38');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Costache','Bogdan','1','Matematica - linia de studiu romana','1','111       ','5,39');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Serban','Attila','22','Informatica - în limba engleza','1','915       ','7,64');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Enache','Robert','1','Matematica - linia de studiu romana','2','121       ','8,63');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Dobre','Larisa','2','Informatica - linia de studiu romana','1','218       ','5,13');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Stoica','Cosmin','2','Informatica - linia de studiu romana','2','224       ','6,94');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Preda','Simona','22','Informatica - în limba engleza','2','921       ','5,45');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Ilie','George','3','Matematica-Informatica - linia de studiu romana','2','321       ','7,24');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Sandu','Adina','2','Informatica - linia de studiu romana','2','223       ','6,15');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Florea','Ciprian','2','Informatica - linia de studiu romana','4','243       ','5,24');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nistor','Bianca','2','Informatica - linia de studiu romana','2','221       ','8,29');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Oprea','Sorin','41','Programare bazata pe componente (în limba engleza)','1','251       ','8,09');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Pavel','Alina','43','Baze de date','1','253       ','9,38');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Morar','Teodor','2','Informatica - linia de studiu romana','1','217       ','7,67');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Badea','Irina','2','Informatica - linia de studiu romana','2','224       ','6,77');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Dragomir','Carmen','2','Informatica - linia de studiu romana','1','218       ','9,79');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Petrescu','Victor','22','Informatica - în limba engleza','4','943       ','7,76');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Popescu','Andrei','22','Informatica - în limba engleza','4','943       ','6,25');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Ionescu','Maria','22','Informatica - în limba engleza','4','942       ','6,89');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Georgescu','Alexandru','12','Informatica - linia de studiu maghiara','2','521       ','9,29');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Dumitrescu','Elena','2','Informatica - linia de studiu romana','4','243       ','7,5');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Stan','Mihai','22','Informatica - în limba engleza','1','911       ','5,81');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Popa','Ioana','22','Informatica - în limba engleza','1','911       ','9,23');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Radu','Vlad','22','Informatica - în limba engleza','1','912       ','7,51');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Marin','Ana','22','Informatica - în limba engleza','1','912       ','5,85');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Voicu','Cristian','22','Informatica - în limba engleza','1','912       ','5,46');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Moldovan','Diana','22','Informatica - în limba engleza','1','912       ','5,38');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Tudor','Paul','22','Informatica - în limba engleza','1','912       ','9,56');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Barbu','Raluca','22','Informatica - în limba engleza','1','912       ','9,35');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Neagu','Zoltan','13','Matematica-Informatica - linia de studiu maghiara','4','641       ','6,47');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Lazar','Denisa','2','Informatica - linia de studiu romana','1','216       ','9,56');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Costache','Bogdan','22','Informatica - în limba engleza','3','933       ','6,68');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Serban','Attila','22','Informatica - în limba engleza','3','933       ','6,87');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Enache','Robert','22','Informatica - în limba engleza','3','933       ','8,85');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Dobre','Larisa','22','Informatica - în limba engleza','3','932       ','7,97');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Stoica','Cosmin','22','Informatica - în limba engleza','2','921       ','5,62');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Preda','Simona','3','Matematica-Informatica - linia de studiu romana','3','332       ','6,75');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Ilie','George','12','Informatica - linia de studiu maghiara','1','511       ','6,04');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Sandu','Adina','12','Informatica - linia de studiu maghiara','1','511       ','7,41');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Florea','Ciprian','12','Informatica - linia de studiu maghiara','1','512       ','7,75');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nistor','Bianca','12','Informatica - linia de studiu maghiara','1','512       ','5,53');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Oprea','Sorin','12','Informatica - linia de studiu maghiara','1','512       ','6,4');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Pavel','Alina','2','Informatica - linia de studiu romana','4','242       ','9,28');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Morar','Teodor','22','Informatica - în limba engleza','2','923       ','6,01');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Badea','Irina','22','Informatica - în limba engleza','2','923       ','5,22');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Dragomir','Carmen','12','Informatica - linia de studiu maghiara','3','531       ','7,02');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Petrescu','Victor','12','Informatica - linia de studiu maghiara','3','531       ','8,67');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Popescu','Andrei','12','Informatica - linia de studiu maghiara','3','531       ','9,91');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Ionescu','Maria','12','Informatica - linia de studiu maghiara','2','521       ','5,3');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Georgescu','Alexandru','2','Informatica - linia de studiu romana','1','211       ','8,76');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Dumitrescu','Elena','2','Informatica - linia de studiu romana','1','212       ','7,28');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Stan','Mihai','3','Matematica-Informatica - linia de studiu romana','1','311       ','9,01');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Popa','Ioana','2','Informatica - linia de studiu romana','3','231       ','5,17');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Radu','Vlad','2','Informatica - linia de studiu romana','3','231       ','6,66');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Marin','Ana','22','Informatica - în limba engleza','1','914       ','8,97');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Voicu','Cristian','22','Informatica - în limba engleza','1','914       ','6,22');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Moldovan','Diana','1','Matematica - linia de studiu romana','1','111       ','5,85');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Tudor','Paul','1','Matematica - linia de studiu romana','1','111       ','8,02');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Barbu','Raluca','22','Informatica - în limba engleza','1','915       ','8,19');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Neagu','Zoltan','22','Informatica - în limba engleza','1','915       ','9,49');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Lazar','Denisa','22','Informatica - în limba engleza','1','915       ','8,41');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Costache','Bogdan','22','Informatica - în limba engleza','2','921       ','5,01');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Serban','Attila','2','Informatica - linia de studiu romana','2','223       ','8,92');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Enache','Robert','2','Informatica - linia de studiu romana','2','223       ','8,02');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Dobre','Larisa','2','Informatica - linia de studiu romana','2','221       ','9,09');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Stoica','Cosmin','2','Informatica - linia de studiu romana','2','221       ','6,26');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Preda','Simona','2','Informatica - linia de studiu romana','1','217       ','8,71');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Ilie','George','2','Informatica - linia de studiu romana','1','217       ','6,13');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Sandu','Adina','2','Informatica - linia de studiu romana','4','243       ','8,71');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Florea','Ciprian','2','Informatica - linia de studiu romana','1','218       ','9,18');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nistor','Bianca','22','Informatica - în limba engleza','4','941       ','7,54');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Oprea','Sorin','22','Informatica - în limba engleza','4','942       ','8,29');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Pavel','Alina','2','Informatica - linia de studiu romana','4','242       ','7,65');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Morar','Teodor','22','Informatica - în limba engleza','3','931       ','6,18');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Badea','Irina','22','Informatica - în limba engleza','3','932       ','5,3');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Dragomir','Carmen','22','Informatica - în limba engleza','2','921       ','7,72');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Petrescu','Victor','22','Informatica - în limba engleza','1','911       ','7,83');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Popescu','Andrei','2','Informatica - linia de studiu romana','2','222       ','7,9');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Ionescu','Maria','2','Informatica - linia de studiu romana','2','222       ','7,42');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Georgescu','Alexandru','2','Informatica - linia de studiu romana','2','222       ','6,15');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Dumitrescu','Elena','2','Informatica - linia de studiu romana','2','222       ','9,22');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Stan','Mihai','22','Informatica - în limba engleza','2','922       ','7,66');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Popa','Ioana','2','Informatica - linia de studiu romana','3','231       ','8,57');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Radu','Vlad','2','Informatica - linia de studiu romana','1','217       ','9,52');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Marin','Ana','2','Informatica - linia de studiu romana','2','221       ','8,13');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Voicu','Cristian','2','Informatica - linia de studiu romana','1','218       ','8,53');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Moldovan','Diana','22','Informatica - în limba engleza','4','941       ','7,9');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Tudor','Paul','22','Informatica - în limba engleza','4','941       ','7,72');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Barbu','Raluca','22','Informatica - în limba engleza','4','942       ','6,88');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Neagu','Zoltan','22','Informatica - în limba engleza','3','931       ','6,15');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Lazar','Denisa','22','Informatica - în limba engleza','3','931       ','5,11');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Costache','Bogdan','22','Informatica - în limba engleza','1','911       ','5,16');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Serban','Attila','22','Informatica - în limba engleza','1','911       ','6,05');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Enache','Robert','22','Informatica - în limba engleza','1','911       ','6,33');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Dobre','Larisa','22','Informatica - în limba engleza','1','911       ','5,77');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Stoica','Cosmin','22','Informatica - în limba engleza','1','911       ','9,62');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Preda','Simona','22','Informatica - în limba engleza','1','912       ','7,66');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Ilie','George','13','Matematica-Informatica - linia de studiu maghiara','4','641       ','7,99');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Sandu','Adina','2','Informatica - linia de studiu romana','1','213       ','7,14');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Florea','Ciprian','2','Informatica - linia de studiu romana','1','213       ','8,93');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nistor','Bianca','2','Informatica - linia de studiu romana','1','214       ','6,2');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Oprea','Sorin','2','Informatica - linia de studiu romana','1','214       ','6,21');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Pavel','Alina','2','Informatica - linia de studiu romana','1','215       ','8,2');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Morar','Teodor','2','Informatica - linia de studiu romana','1','216       ','7,95');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Badea','Irina','2','Informatica - linia de studiu romana','1','216       ','9,94');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Dragomir','Carmen','22','Informatica - în limba engleza','3','933       ','7,58');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Petrescu','Victor','22','Informatica - în limba engleza','3','931       ','6,74');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Popescu','Andrei','3','Matematica-Informatica - linia de studiu romana','4','341       ','8');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Ionescu','Maria','3','Matematica-Informatica - linia de studiu romana','4','341       ','9,55');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Georgescu','Alexandru','22','Informatica - în limba engleza','1','913       ','6,39');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Dumitrescu','Elena','22','Informatica - în limba engleza','1','914       ','7,37');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Stan','Mihai','12','Informatica - linia de studiu maghiara','1','512       ','5,08');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Popa','Ioana','2','Informatica - linia de studiu romana','4','243       ','5,69');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Radu','Vlad','13','Matematica-Informatica - linia de studiu maghiara','3','631       ','6,76');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Marin','Ana','12','Informatica - linia de studiu maghiara','4','541       ','9,01');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Voicu','Cristian','3','Matematica-Informatica - linia de studiu romana','4','342       ','6,55');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Moldovan','Diana','2','Informatica - linia de studiu romana','4','242       ','8,54');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Tudor','Paul','22','Informatica - în limba engleza','2','923       ','6,81');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Barbu','Raluca','2','Informatica - linia de studiu romana','3','233       ','5,74');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Neagu','Zoltan','12','Informatica - linia de studiu maghiara','3','531       ','5,97');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Lazar','Denisa','12','Informatica - linia de studiu maghiara','2','521       ','7,42');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Costache','Bogdan','2','Informatica - linia de studiu romana','4','244       ','8,81');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Serban','Attila','2','Informatica - linia de studiu romana','1','211       ','6,29');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Enache','Robert','2','Informatica - linia de studiu romana','1','211       ','9,76');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Dobre','Larisa','2','Informatica - linia de studiu romana','1','211       ','5,51');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Stoica','Cosmin','2','Informatica - linia de studiu romana','3','231       ','8,31');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Preda','Simona','2','Informatica - linia de studiu romana','2','221       ','7,91');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Ilie','George','2','Informatica - linia de studiu romana','2','221       ','5,31');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Sandu','Adina','22','Informatica - în limba engleza','1','914       ','9,17');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Florea','Ciprian','22','Informatica - în limba engleza','1','914       ','7,44');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nistor','Bianca','22','Informatica - în limba engleza','1','914       ','6,66');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Oprea','Sorin','22','Informatica - în limba engleza','1','915       ','9,03');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Pavel','Alina','22','Informatica - în limba engleza','1','915       ','9,11');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Morar','Teodor','2','Informatica - linia de studiu romana','4','241       ','5,62');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Badea','Irina','1','Matematica - linia de studiu romana','3','131       ','9,1');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Dragomir','Carmen','1','Matematica - linia de studiu romana','1','111       ','9,16');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Petrescu','Victor','2','Informatica - linia de studiu romana','4','244       ','5,24');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Popescu','Andrei','22','Informatica - în limba engleza','2','922       ','5,31');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Ionescu','Maria','2','Informatica - linia de studiu romana','1','218       ','7,52');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Georgescu','Alexandru','22','Informatica - în limba engleza','2','922       ','7,68');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Dumitrescu','Elena','22','Informatica - în limba engleza','2','922       ','9,93');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Stan','Mihai','13','Matematica-Informatica - linia de studiu maghiara','2','621       ','5,27');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Popa','Ioana','48','Optimizarea modelelor informatice','1','257       ','7,8');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Radu','Vlad','3','Matematica-Informatica - linia de studiu romana','1','311       ','7,56');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Marin','Ana','2','Informatica - linia de studiu romana','1','217       ','7,92');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Voicu','Cristian','22','Informatica - în limba engleza','2','922       ','9,11');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Moldovan','Diana','2','Informatica - linia de studiu romana','2','221       ','6,71');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Tudor','Paul','2','Informatica - linia de studiu romana','2','224       ','9,59');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Barbu','Raluca','22','Informatica - în limba engleza','4','941       ','8,14');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Neagu','Zoltan','22','Informatica - în limba engleza','4','943       ','6,51');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Lazar','Denisa','22','Informatica - în limba engleza','4','942       ','5,58');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Costache','Bogdan','22','Informatica - în limba engleza','3','931       ','5,08');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Serban','Attila','22','Informatica - în limba engleza','3','932       ','6,81');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Enache','Robert','22','Informatica - în limba engleza','3','932       ','8,43');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Dobre','Larisa','22','Informatica - în limba engleza','1','911       ','8,69');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Stoica','Cosmin','22','Informatica - în limba engleza','1','911       ','6,71');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Preda','Simona','22','Informatica - în limba engleza','1','912       ','9,52');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Ilie','George','2','Informatica - linia de studiu romana','1','214       ','6,11');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Sandu','Adina','2','Informatica - linia de studiu romana','1','215       ','8,26');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Florea','Ciprian','2','Informatica - linia de studiu romana','1','216       ','9,1');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nistor','Bianca','2','Informatica - linia de studiu romana','1','217       ','5,01');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Oprea','Sorin','22','Informatica - în limba engleza','3','931       ','8,39');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Pavel','Alina','22','Informatica - în limba engleza','3','931       ','7,03');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Morar','Teodor','22','Informatica - în limba engleza','3','931       ','8,66');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Badea','Irina','22','Informatica - în limba engleza','3','932       ','7,01');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Dragomir','Carmen','3','Matematica-Informatica - linia de studiu romana','4','341       ','6,47');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Petrescu','Victor','11','Matematica - linia de studiu maghiara','3','431       ','9,24');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Popescu','Andrei','22','Informatica - în limba engleza','1','913       ','5,93');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Ionescu','Maria','22','Informatica - în limba engleza','1','913       ','7,07');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Georgescu','Alexandru','22','Informatica - în limba engleza','1','913       ','6,53');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Dumitrescu','Elena','12','Informatica - linia de studiu maghiara','1','513       ','9,23');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Stan','Mihai','12','Informatica - linia de studiu maghiara','1','511       ','8,47');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Popa','Ioana','12','Informatica - linia de studiu maghiara','1','511       ','7,08');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Radu','Vlad','12','Informatica - linia de studiu maghiara','1','511       ','8,54');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Marin','Ana','12','Informatica - linia de studiu maghiara','1','511       ','8,53');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Voicu','Cristian','12','Informatica - linia de studiu maghiara','4','541       ','5,33');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Moldovan','Diana','3','Matematica-Informatica - linia de studiu romana','3','331       ','7,93');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Tudor','Paul','3','Matematica-Informatica - linia de studiu romana','3','331       ','8');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Barbu','Raluca','3','Matematica-Informatica - linia de studiu romana','3','331       ','9,35');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Neagu','Zoltan','22','Informatica - în limba engleza','1','913       ','8,66');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Lazar','Denisa','22','Informatica - în limba engleza','2','923       ','9,83');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Costache','Bogdan','22','Informatica - în limba engleza','2','923       ','8,49');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Serban','Attila','12','Informatica - linia de studiu maghiara','3','531       ','5,39');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Enache','Robert','12','Informatica - linia de studiu maghiara','3','531       ','5,97');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Dobre','Larisa','12','Informatica - linia de studiu maghiara','2','521       ','5,87');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Stoica','Cosmin','2','Informatica - linia de studiu romana','1','211       ','5,35');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Preda','Simona','2','Informatica - linia de studiu romana','1','212       ','5,74');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Ilie','George','2','Informatica - linia de studiu romana','1','212       ','8,63');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Sandu','Adina','2','Informatica - linia de studiu romana','3','231       ','6,73');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Florea','Ciprian','2','Informatica - linia de studiu romana','3','231       ','7,36');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nistor','Bianca','2','Informatica - linia de studiu romana','3','231       ','8,26');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Oprea','Sorin','2','Informatica - linia de studiu romana','3','231       ','5,26');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Pavel','Alina','2','Informatica - linia de studiu romana','3','231       ','8,7');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Morar','Teodor','22','Informatica - în limba engleza','1','915       ','9,55');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Badea','Irina','1','Matematica - linia de studiu romana','1','111       ','6,34');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Dragomir','Carmen','2','Informatica - linia de studiu romana','4','242       ','6,94');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Petrescu','Victor','22','Informatica - în limba engleza','2','922       ','6,74');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Popescu','Andrei','22','Informatica - în limba engleza','2','921       ','7,04');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Ionescu','Maria','3','Matematica-Informatica - linia de studiu romana','2','321       ','8,5');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Georgescu','Alexandru','3','Matematica-Informatica - linia de studiu romana','2','321       ','9,99');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Dumitrescu','Elena','47','Modelare si simulare','1','256       ','5,64');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Stan','Mihai','2','Informatica - linia de studiu romana','2','221       ','5,94');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Popa','Ioana','2','Informatica - linia de studiu romana','2','222       ','8,06');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Radu','Vlad','2','Informatica - linia de studiu romana','2','222       ','5,23');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Marin','Ana','2','Informatica - linia de studiu romana','2','221       ','5,06');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Voicu','Cristian','2','Informatica - linia de studiu romana','2','224       ','9,12');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Moldovan','Diana','22','Informatica - în limba engleza','4','941       ','5,41');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Tudor','Paul','22','Informatica - în limba engleza','4','941       ','9,73');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Barbu','Raluca','22','Informatica - în limba engleza','4','943       ','6,44');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Neagu','Zoltan','22','Informatica - în limba engleza','4','943       ','8,04');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Lazar','Denisa','22','Informatica - în limba engleza','4','943       ','5,37');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Costache','Bogdan','22','Informatica - în limba engleza','3','931       ','9,35');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Serban','Attila','22','Informatica - în limba engleza','3','932       ','9,6');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Enache','Robert','22','Informatica - în limba engleza','3','932       ','8,65');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Dobre','Larisa','22','Informatica - în limba engleza','3','932       ','5,08');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Stoica','Cosmin','22','Informatica - în limba engleza','2','922       ','5,88');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Preda','Simona','22','Informatica - în limba engleza','1','911       ','8,74');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Ilie','George','22','Informatica - în limba engleza','1','911       ','7,77');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Sandu','Adina','22','Informatica - în limba engleza','1','911       ','7,29');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Florea','Ciprian','22','Informatica - în limba engleza','1','911       ','8,74');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nistor','Bianca','22','Informatica - în limba engleza','1','912       ','8,83');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Oprea','Sorin','2','Informatica - linia de studiu romana','1','213       ','7,5');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Pavel','Alina','2','Informatica - linia de studiu romana','1','213       ','6,19');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Morar','Teodor','2','Informatica - linia de studiu romana','1','216       ','5,78');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Badea','Irina','2','Informatica - linia de studiu romana','1','217       ','6,08');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Dragomir','Carmen','22','Informatica - în limba engleza','3','933       ','5,57');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Petrescu','Victor','22','Informatica - în limba engleza','3','933       ','5,41');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Popescu','Andrei','22','Informatica - în limba engleza','3','932       ','8,82');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Ionescu','Maria','3','Matematica-Informatica - linia de studiu romana','4','341       ','5,58');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Georgescu','Alexandru','3','Matematica-Informatica - linia de studiu romana','4','341       ','7,03');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Dumitrescu','Elena','22','Informatica - în limba engleza','1','913       ','5,32');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Stan','Mihai','22','Informatica - în limba engleza','1','914       ','8,56');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Popa','Ioana','12','Informatica - linia de studiu maghiara','1','512       ','8,94');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Radu','Vlad','2','Informatica - linia de studiu romana','4','241       ','7,41');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Marin','Ana','13','Matematica-Informatica - linia de studiu maghiara','2','621       ','8,88');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Voicu','Cristian','12','Informatica - linia de studiu maghiara','4','541       ','9,88');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Moldovan','Diana','5','Matematici aplicate','2','122       ','7,61');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Tudor','Paul','3','Matematica-Informatica - linia de studiu romana','4','342       ','5,8');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Barbu','Raluca','2','Informatica - linia de studiu romana','3','232       ','5,71');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Neagu','Zoltan','3','Matematica-Informatica - linia de studiu romana','4','342       ','7,3');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Lazar','Denisa','22','Informatica - în limba engleza','2','923       ','8,4');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Costache','Bogdan','22','Informatica - în limba engleza','2','923       ','6,11');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Serban','Attila','2','Informatica - linia de studiu romana','3','233       ','7,97');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Enache','Robert','2','Informatica - linia de studiu romana','3','233       ','6,33');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Dobre','Larisa','12','Informatica - linia de studiu maghiara','3','531       ','6,02');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Stoica','Cosmin','12','Informatica - linia de studiu maghiara','2','521       ','8,34');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Preda','Simona','12','Informatica - linia de studiu maghiara','2','521       ','6,14');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Ilie','George','12','Informatica - linia de studiu maghiara','2','521       ','7,45');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Sandu','Adina','2','Informatica - linia de studiu romana','1','211       ','7,32');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Florea','Ciprian','3','Matematica-Informatica - linia de studiu romana','1','311       ','8,63');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nistor','Bianca','2','Informatica - linia de studiu romana','3','232       ','5,68');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Oprea','Sorin','22','Informatica - în limba engleza','1','914       ','5,57');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Pavel','Alina','22','Informatica - în limba engleza','1','914       ','9,54');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Morar','Teodor','22','Informatica - în limba engleza','1','915       ','9,68');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Badea','Irina','22','Informatica - în limba engleza','1','915       ','5,77');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Dragomir','Carmen','12','Informatica - linia de studiu maghiara','1','513       ','6,71');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Petrescu','Victor','22','Informatica - în limba engleza','1','915       ','6,51');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Popescu','Andrei','2','Informatica - linia de studiu romana','4','241       ','8,46');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Ionescu','Maria','2','Informatica - linia de studiu romana','4','244       ','9,04');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Georgescu','Alexandru','43','Baze de date','1','253       ','5,64');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Dumitrescu','Elena','22','Informatica - în limba engleza','2','921       ','6,14');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Stan','Mihai','22','Informatica - în limba engleza','2','921       ','5,73');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Popa','Ioana','3','Matematica-Informatica - linia de studiu romana','2','321       ','8,3');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Radu','Vlad','2','Informatica - linia de studiu romana','2','223       ','5,38');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Marin','Ana','3','Matematica-Informatica - linia de studiu romana','2','321       ','5,45');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Voicu','Cristian','2','Informatica - linia de studiu romana','4','243       ','9,25');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Moldovan','Diana','2','Informatica - linia de studiu romana','2','222       ','9,23');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Tudor','Paul','22','Informatica - în limba engleza','2','922       ','7,21');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Barbu','Raluca','22','Informatica - în limba engleza','4','943       ','9,45');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Neagu','Zoltan','22','Informatica - în limba engleza','4','942       ','5,78');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Lazar','Denisa','22','Informatica - în limba engleza','1','914       ','8,19');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Costache','Bogdan','2','Informatica - linia de studiu romana','4','243       ','7,14');